derp = [ Socket {
    nsp: 
     Namespace {
       name: '/',
       server: [Object],
       sockets: [Object],
       connected: [Object],
       fns: [],
       ids: 0,
       adapter: [Object],
       _events: [Object],
       _eventsCount: 1 },
    server: 
     Server {
       nsps: [Object],
       _path: '/socket.io',
       _serveClient: true,
       _adapter: [Function: Adapter],
       _origins: '*:*',
       sockets: [Object],
       eio: [Object],
       httpServer: [Object],
       engine: [Object] },
    adapter: 
     Adapter {
       nsp: [Object],
       rooms: [Object],
       sids: [Object],
       encoder: Encoder {} },
    id: 'OFCIxutaCIXEk_IyAAAA',
    client: 
     Client {
       server: [Object],
       conn: [Object],
       encoder: Encoder {},
       decoder: [Object],
       id: 'OFCIxutaCIXEk_IyAAAA',
       request: [Object],
       onclose: [Function: bound ],
       ondata: [Function: bound ],
       onerror: [Function: bound ],
       ondecoded: [Function: bound ],
       sockets: [Object],
       nsps: [Object],
       connectBuffer: [] },
    conn: 
     Socket {
       id: 'OFCIxutaCIXEk_IyAAAA',
       server: [Object],
       upgrading: false,
       upgraded: true,
       readyState: 'open',
       writeBuffer: [],
       packetsFn: [],
       sentCallbackFn: [],
       cleanupFn: [Object],
       request: [Object],
       remoteAddress: '::1',
       checkIntervalTimer: null,
       upgradeTimeoutTimer: null,
       pingTimeoutTimer: [Object],
       transport: [Object],
       _events: [Object],
       _eventsCount: 3 },
    rooms: { OFCIxutaCIXEk_IyAAAA: 'OFCIxutaCIXEk_IyAAAA' },
    acks: {},
    connected: true,
    disconnected: false,
    handshake: 
     { headers: [Object],
       time: 'Thu Feb 09 2017 15:30:49 GMT-0800 (PST)',
       address: '::1',
       xdomain: false,
       secure: false,
       issued: 1486683049247,
       url: '/socket.io/?EIO=3&transport=polling&t=LebDmqC',
       query: [Object] },
    fns: [],
    _events: { 'chat message': [Object], shuffle: [Function] },
    _eventsCount: 2 } ]